# School

Bir **Warm-Up** etkinliği ve hızlı bir `SELECT` ifadesiyle başlayalım.

## Data
Bu URL'de bulunan `school.sqlite` database ile çalışacağız:
`https://wagon-public-datasets.s3.amazonaws.com/sql_databases/school.sqlite`

Dosyayı indirmek için aşağıdaki hücreyi çalıştırın:

In [1]:
!curl https://wagon-public-datasets.s3.amazonaws.com/sql_databases/school.sqlite > data/school.sqlite

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12288  100 12288    0     0  37422      0 --:--:-- --:--:-- --:--:-- 37349

## Database Discovery

Database'i keşfetmek için (database'i indirdikten sonra) VS Code SQLite extension'ını kullanabilirsiniz:

- `Ctrl-Shift-P` veya `Cmd-Shift-P` tuşlarına basın
- `SQLite: Open Database` görünene kadar yazmaya başlayın
- `Enter`
- Açılan listeden database dosyasını seçin
- Sol alt köşede `SQLITE EXPLORER` butonuna tıklayın

Aşağıdaki soruları cevaplayın:

- Kaç tane table var?
- Her table için column'lar neler?

Schema ile rahat ettiğinizde bir SQL Query yazalım.

## Setup

Pandas ve sqlite3 ihtiyacımız olan her şey :-)

In [5]:
import pandas as pd
from sqlite3 import connect

## Paris Students

👉 `Paris` şehrinden tüm students kayıtlarını seçmek için bir SQL Query yaz.

In [18]:
# Paris'ten gelen tüm öğrencileri retun et
query_students = """
    SELECT * from students limit 100
"""

In [21]:
with connect('data/school.sqlite') as conn:
    df = pd.read_sql(
        query_students,
        con=conn
    )
df

   id first_name   last_name birth_city
0   1       Oran    Southern      Paris
1   2       Safa        Lugo     London
2   3       Huda    Goulding     Berlin
3   4     Kavita      Hilton     Berlin
4   5       Rick  Broadhurst     London
5   6     Bertha       Brook      Paris
6   7       Neha     Salazar      Paris
7   8     Ignacy       Casey      Paris
8   9        Mai       Crane   Brussels
9  10    Shirley       Mayer      Paris

## Dynamic queries

Harika, Paris öğrencilerini aldık.

Ama bu sorgunun **dinamik** olması (yani herhangi bir şehirle çalışması) güzel olmaz mıydı?

👉 Sorguyu, herhangi bir şehir için kullanabileceğimiz şekilde yeniden yazın. Aşağıdaki kodda, DataFrame’i yüklerken bunu nasıl kullanacağımızı görebilirsiniz.

In [23]:
# City den gelen tüm öğrencileri retun et
query_students = """
   SELECT * from students where birth_city = ?
"""

In [24]:
city = 'Brussels'

with connect('data/school.sqlite') as conn:
    df = pd.read_sql(
        query_students,
        con=conn,
        params=[city]  # Burası parametreyi, yani city değerini ilettiğimiz yer.
    )
df.head()

   id first_name last_name birth_city
0   9        Mai     Crane   Brussels

Sonuç beklediğiniz gibi göründüğünde, sorgunuzu test etmek için aşağıdaki hücreyi çalıştırın.

In [27]:
from nbresult import ChallengeResult
result = ChallengeResult(
    'school',
    query=query_students
)
result.write(); print(result.check())

============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/gonul/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/gonul/workintech_project/data_back_to_school_query/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 5 items

test_school.py::TestSchool::test_barcelona PASSED                        [ 20%]
test_school.py::TestSchool::test_berlin PASSED                           [ 40%]
test_school.py::TestSchool::test_brussels PASSED                         [ 60%]
test_school.py::TestSchool::test_london PASSED                           [ 80%]
test_school.py::TestSchool::test_paris PASSED                            [100%]

============================== 5 passed in 0.01s ===============================


💯 You can commit your code:

git add tests/school.pickle

git commit -m 'Completed school step'

git push origin master

## Key learning points

- Bir database üzerinde query yazmak için Pandas kullanın
- Dinamik queries yazmak için parameter substitution kullanın